# Generated by Django 3.0.5 on 2020-04-14 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniContact',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('graduation_year', models.PositiveSmallIntegerField(default=2020)),
                ('branch', models.CharField(choices=[('Chemical Engineering', 'Chemical Engineering'), ('Civil Engineering', 'Civil Engineering'), ('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Electronics and Communication Engineering', 'Electronics and Communication Engineering'), ('Information Technology', 'Information Technology'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Metallurgical and Materials Engineering', 'Metallurgical and Materials Engineering'), ('Mining Engineering', 'Mining Engineering'), ('Unknown', 'Unknown')], max_length=50)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20)),
                ('current_country', models.CharField(blank=True, default='', max_length=50)),
                ('company', models.CharField(blank=True, default='', max_length=50)),
                ('university_for_higher_studies', models.CharField(blank=True, default='', max_length=100)),
                ('specialisation_for_higher_studies', models.CharField(blank=True, default='', max_length=100)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlumniContactInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=100)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.AlumniContact')),
            ],
        ),
    ]
